apply plugin: 'com.android.application'
apply plugin: 'realm-android'

android {
    compileSdkVersion 36
    defaultConfig {
        applicationId "dev.erfangh.mobilegis"
        minSdkVersion 26
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    //DataBinding
    dataBinding {
        enabled = true
    }
    realm {
        syncEnabled = true
    }
    compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
    }
    namespace 'dev.erfangh.mobilegis'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', 'osmbonuspack_v6.5.1.aar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.10.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

    //osmdroid map library
    implementation 'org.osmdroid:osmdroid-android:6.1.20'
    implementation('com.github.MKergall:osmbonuspack:6.5.1')
            {
                exclude group: 'com.android.support'
                exclude module: 'appcompat-v7'
                exclude module: 'support-v4'
            }

    //RxJava library
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'

    //Retrofit library
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'

    //color picker
    implementation 'com.github.QuadFlask:colorpicker:0.0.15'

    //Dagger 2
    implementation 'com.google.dagger:dagger:2.59.2'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.59.2'

    implementation 'com.google.dagger:dagger-android:2.59.2'
    implementation 'com.google.dagger:dagger-android-support:2.59.2'
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.59.2'
}
